name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checkout the code to current branch
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        make install
    - name : Format the code with black
      run: |
        make format
    - name: Analysing the code with pylint
      run: |
        make lint
    - name : Run the tests
      run: |
        make tests
  
